package com.seancoyle.core.ui.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val primaryColor = Color(0xFFFFFFFF)
internal val primaryContainerColor = Color(0xFF03A9F4)
internal val backgroundColor = Color(0xFF212121)
internal val secondaryColor = Color(0xFF424242)
internal val surfaceColor = Color(0xFF424242)
internal val errorColor = Color(0xFFE4342D)
internal val textPrimaryColor = Color(0xFFFFFFFF)
internal val textSecondaryColor = Color(0xFF000000)

internal val black = Color(0xFF000000)
internal val white = Color(0xFFFFFFFF)
internal val transparent = Color(0x00000000)

internal val md_theme_light_primary = Color(0xFF006493)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFCAE6FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001E30)
internal val md_theme_light_secondary = Color(0xFF50606E)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFD3E5F5)
internal val md_theme_light_onSecondaryContainer = Color(0xFF0C1D29)
internal val md_theme_light_tertiary = Color(0xFF9C432E)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFDAD2)
internal val md_theme_light_onTertiaryContainer = Color(0xFF3D0700)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFF8FDFF)
internal val md_theme_light_onBackground = Color(0xFF001F25)
internal val md_theme_light_surface = Color(0xFFF8FDFF)
internal val md_theme_light_onSurface = Color(0xFF001F25)
internal val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
internal val md_theme_light_onSurfaceVariant = Color(0xFF41474D)
internal val md_theme_light_outline = Color(0xFF72787E)
internal val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
internal val md_theme_light_inverseSurface = Color(0xFF00363F)
internal val md_theme_light_inversePrimary = Color(0xFF8DCDFF)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF006493)
internal val md_theme_light_outlineVariant = Color(0xFFC1C7CE)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF8DCDFF)
internal val md_theme_dark_onPrimary = Color(0xFF00344F)
internal val md_theme_dark_primaryContainer = Color(0xFF004B70)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFCAE6FF)
internal val md_theme_dark_secondary = Color(0xFFD3E5F5)
internal val md_theme_dark_onSecondary = Color(0xFF22323F)
internal val md_theme_dark_secondaryContainer = Color(0xFF384956)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFD3E5F5)
internal val md_theme_dark_tertiary = Color(0xFFFFB4A3)
internal val md_theme_dark_onTertiary = Color(0xFF5E1606)
internal val md_theme_dark_tertiaryContainer = Color(0xFF7D2C19)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD2)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF212121)
internal val md_theme_dark_onBackground = Color(0xFFA6EEFF)
internal val md_theme_dark_surface = Color(0xFF424242)
internal val md_theme_dark_onSurface = Color(0xFFA6EEFF)
internal val md_theme_dark_surfaceVariant = Color(0xFF41474D)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
internal val md_theme_dark_outline = Color(0xFF8B9198)
internal val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
internal val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
internal val md_theme_dark_inversePrimary = Color(0xFF006493)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF8DCDFF)
internal val md_theme_dark_outlineVariant = Color(0xFF41474D)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF03A9F4)
internal val Green90 = Color(0xFF5AFF9D)