object Modules {
    const val app = ":app"
    const val core = ":core"
    const val coreDatabase = ":core-database"
    const val coreDatastore = ":core-datastore"
    const val coreTesting = ":core-testing"
    const val launch = ":launch"
    const val launchConstants = ":launch:launch-constants"
    const val launchDataSource = ":launch:launch-datasource"
    const val launchDataSourceTest = ":launch:launch-datasource-test"
    const val launchModels = ":launch:launch-models"
    const val launchUseCases = ":launch:launch-usecases"
    const val launchViewState = ":launch:launch-viewstate"
    const val uiBase = ":ui-base"
    const val uiLaunch = ":launch:ui-launch"
}