name: Compare APK Sizes

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  apk-size:
    name: Analyse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download branch APK
        uses: actions/download-artifact@v4
        with:
          name: spacex-debug_${{ inputs.version }}

      - name: Download main APK
        uses: actions/download-artifact@v4
        with:
          name: spacex-debug-main

      - name: Compare APK sizes
        run: .github/scripts/compare_apk_sizes.sh "${{ inputs.version }}"

      # Create or update comment with APK size
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "APK size"

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **APK Size Report**
                  
            ${{ env.OUTPUT }}

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            **APK Size Report**

            ${{ env.OUTPUT }}