name: App Version

on:
  workflow_call:
    outputs:
      version:
        description: "The current version name"
        value: ${{ jobs.get-version-name.outputs.version }}

jobs:
  get-version-name:
    name: Fetch
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Runs script to get app version from a gradle task
      - name: Get version
        id: get-version
        run: .github/scripts/get_version.sh
