name: Build Dev Release APK
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build-and-sign.yml
    with:
      version:        ${{ inputs.version }}
      assembleScript: .github/scripts/assemble_release_apk.sh
      outputDir:      app/build/outputs/apk/release
      unsignedName:   app-release-unsigned-signed.apk
      artifactPrefix: spacexDev-release
    secrets:
      signingKey:       ${{ secrets.TEST_SIGNING_KEY }}
      alias:            ${{ secrets.TEST_ALIAS }}
      keyStorePassword: ${{ secrets.TEST_KEY_STORE_PASSWORD }}
      keyPassword:      ${{ secrets.TEST_KEY_PASSWORD }}
