name: Build Dev Release APK
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    outputs:
      artifactName:
        value: ${{ jobs.build.outputs.artifactName }}

jobs:
  build:
    uses: ./.github/workflows/build_sign.yml
    with:
      assembleScript: .github/scripts/assemble_release_apk.sh
      outputDir:      app/build/outputs/apk/release
      unsignedName:   app-release-unsigned-signed.apk
      artifactName:   spacexDev-release_${{ inputs.version }}.apk
    secrets:
      signingKey:       ${{ secrets.TEST_SIGNING_KEY }}
      alias:            ${{ secrets.TEST_ALIAS }}
      keyStorePassword: ${{ secrets.TEST_KEY_STORE_PASSWORD }}
      keyPassword:      ${{ secrets.TEST_KEY_PASSWORD }}
