name: Build

on:
  workflow_call:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: |
          bash ./gradlew :app:assembleDebug
          
          # Get the app version dynamically from the build
          VERSION=$(./gradlew -q printAppVersionName)
          
          # Export VERSION to GitHub Actions environment
          echo "VERSION=${VERSION}" >> $GITHUB_ENV  
          
          # Rename APK to match the desired format
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/spacexDev-release_${VERSION}.apk

      - name: Upload branch APK
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: spacexDev-release_${{ env.VERSION }}
          path: app/build/outputs/apk/debug/spacexDev-release_${{ env.VERSION }}.apk

      # Get Artifact URL for the QR Code
      - name: Get Artifact URL
        id: get-artifact-url
        run: |
          # Get artifact ID using GitHub API
          ARTIFACT_ID=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" | \
            jq -r ".artifacts[] | select(.name==\"spacexDev-release_${{ env.VERSION }}\") | .id")
          
          # Construct the full artifact URL
          artifact_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/$ARTIFACT_ID"
          
          # Output the artifact URL
          echo "Artifact URL: $artifact_url"
          echo "::set-output name=artifact_url::$artifact_url"

      # Debugging: List all PR comments
      - name: List PR Comments (Debugging)
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      # Find Existing PR Comment
      - name: Find PR Comment
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ":rocket: Scan this QR code to download the APK."

      # Delete Existing Comment (if found)
      - name: Delete PR Comment (if exists)
        if: steps.find-comment.outputs.comment-id
        run: |
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ steps.find-comment.outputs.comment-id }}"

      # Post or Update PR Comment with QR Code
      - name: Post or Update PR Comment with APK QR Code
        uses: kentaro-m/qr-code-commenter-action@v0.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content: "${{ steps.get-artifact-url.outputs.artifact_url }}"
          comment-id: "${{ steps.find-comment.outputs.comment-id }}"
          comment: |
            :rocket: Scan this QR code to download the APK.
            {qrcode}