name: Commit Version Bump

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact-name: { description: "Name of uploaded artifact", type: string, required: true }
      file-path: { description: "Location of file", type: string, required: true }

jobs:
  commit-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.file-path }}

      - name: Move bumped file back
        run: mv version-bump/buildSrc/src/main/kotlin/Android.kt buildSrc/src/main/kotlin/Android.kt

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          message: "[RELEASE BOT]: commit version bump"
