name: Generate QR Code

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Date/Time
        id: datetime
        run: .github/scripts/get_current_datetime.sh

      # Build URL for the APK artifact
      - name: Get APK URL
        id: get-artifact-url
        run: .github/scripts/get_dev_release_url.sh "${{ secrets.GITHUB_TOKEN }}" "${{ github.repository }}" "${{ github.run_id }}" "spacexDev-release_${{ inputs.version }}"

      # Generates QR code message for PR comment
      - name: Render comment body
        id: render-comment
        run: .github/scripts/render_qr_code_comment.sh \
          "${{ steps.get-artifact-url.outputs.artifact_url }}" \
          "${{ steps.get-artifact-url.outputs.artifact_url_encoded }}" \
          "${{ inputs.version }}" \
          "${{ env.datetime }}"

      # Create or update comment with QR code
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Scan this QR code to download the release APK.

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: ${{ steps.render-comment.outputs.comment_file }}

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body-path: ${{ steps.render-comment.outputs.comment_file }}