name: Deploy to PLay Store

on:
  push:
    branches:
      - main

jobs:

  unit-tests:
    uses: ./.github/workflows/unit_test.yml

  ui-tests:
    uses: ./.github/workflows/ui_test.yml
    secrets: inherit

  # Bump the version code and name only after tests pass
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    #needs: [unit-tests, ui-tests]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Version Bump
        id: version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: 1.0.0

  build-sign:
    name: Build & Sign
    runs-on: ubuntu-latest
    needs: version-bump

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Build release AAB
      - name: Assemble Release Bundle
        run: ./gradlew :app:bundleRelease --stacktrace

      # Get app version
      - name: Get App Version
        id: get_version
        run: |
          VERSION=$(./gradlew -q printAppVersionName)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Sign the production bundle
      - name: Sign Android Production Release
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      # Rename Signed AAB
      - name: Rename Signed AAB
        run: mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/spacex-release_${VERSION}.aab

      # Debug: List files to check if the AAB file exists
      - name: List Files in Release Directory
        run: ls -al app/build/outputs/bundle/release/

      # Upload Signed AAB
      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: app/build/outputs/bundle/release/spacex-release_${VERSION}.aab

  # Deploy to Google Play
  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    needs: build-sign

    steps:
      # Download Signed AAB
      - name: Download AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-bundle
          path: app/build/outputs/bundle/release/

      # Deploy to Play store
      - name: Deploy Bundle to google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH_JSON }}
          packageName: com.seancoyle.spacex
          releaseFiles: app/build/outputs/bundle/release/spacex-release_${{ env.VERSION }}.aab
          track: internal
          status: "completed"
          whatsNewDirectory: whatsNew