name: Deploy to PLay Store

on:
  push:
    branches:
      - main

jobs:

  unit-tests:
    uses: ./.github/workflows/unit_test.yml

  ui-tests:
    uses: ./.github/workflows/ui_test.yml
    secrets: inherit

  # Bump the version code and name only after tests pass
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    #needs: [unit-tests, ui-tests]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Version Bump
        id: version
        run: |
          file="buildSrc/src/main/kotlin/Android.kt"
          currentVersionName=$(./gradlew -q printAppVersionName)
          currentVersionCode=$(./gradlew -q printAppVersionCode)
          
          # Correctly split versionName (e.g. 1.8.0 → major=1, minor=8, patch=0)
          IFS='.' read -r major minor patch <<< "$currentVersionName"
  
          # Bump minor version
          newMinor=$((minor + 1))
          newVersionName="$major.$newMinor.$patch"
          
          # Replace versionName in Android.kt
          sed -i -E "s/(versionName = \")[^\"]+(\")/\1${newVersionName}\2/" "$file"
          echo "Updated versionName to $newVersionName"
          
          # Extract and bump versionCode
          currentVersionCode=$(grep 'versionCode' "$file" | sed -E 's/.*= ([0-9]+)/\1/')
          newVersionCode=$((currentVersionCode + 1))
          
          # Replace versionCode in Android.kt
          sed -i -E "s/(versionCode = )([0-9]+)/\1$newVersionCode/" "$file"
          echo "Updated versionCode to $newVersionCode"
          
          # Export for commit message
          echo "version=$newVersionName" >> $GITHUB_OUTPUT

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-sign:
    name: Build & Sign
    runs-on: ubuntu-latest
    needs: version-bump

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Build release AAB
      - name: Assemble Release Bundle
        run: ./gradlew :app:bundleRelease --stacktrace

      # Sign the production bundle
      - name: Sign Android Production Release
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      # Rename Signed AAB
      - name: Rename Signed AAB
        run: mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/spacex-release_${{ needs.version-bump.outputs.version }}.aab

      # Upload Signed AAB
      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: app/build/outputs/bundle/release/spacex-release_${{ needs.version-bump.outputs.version }}.aab

  # Deploy to Google Play
  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    needs: build-sign

    steps:
      # Download Signed AAB
      - name: Download AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-bundle
          path: app/build/outputs/bundle/release/

      # Deploy to Play store
      - name: Deploy Bundle to google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH_JSON }}
          packageName: com.seancoyle.spacex
          releaseFiles: app/build/outputs/bundle/release/spacex-release_${{ needs.version-bump.outputs.version }}.aab
          track: internal
          status: "completed"
#          whatsNewDirectory: whatsNew