name: Deploy to PLay Store

on:
  push:
    branches:
      - main

jobs:

  unit-tests:
    uses: ./.github/workflows/unit_test.yml

  ui-tests:
    uses: ./.github/workflows/ui_test.yml
    secrets: inherit

  version-bump:
    uses: ./.github/workflows/version_bump.yml
    #needs: [unit-tests, ui-tests]
    secrets: inherit

  assemble-release:
    uses: ./.github/workflows/assemble_release_aab.yml
    needs: version-bump
    secrets: inherit
    with:
      version: ${{ needs.version-bump.outputs.version }}

  deploy-playstore:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    needs: [assemble-release, version-bump]

    steps:
      # Download Signed AAB
      - name: Download AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-bundle
          path: app/build/outputs/bundle/release/

      # Deploy to Play store
      - name: Deploy Bundle to google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH_JSON }}
          packageName: com.seancoyle.spacex
          releaseFiles: app/build/outputs/bundle/release/spacex-release_${{ needs.version-bump.outputs.version  }}.aab
          track: internal
          status: "completed"
#          whatsNewDirectory: whatsNew