name: Deploy to PLay Store

on:
  push:
    branches:
      - main

jobs:

  unit-tests:
    uses: ./.github/workflows/unit_test.yml

  ui-tests:
    uses: ./.github/workflows/ui_test.yml
    secrets: inherit

  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Bump the version code and name
      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: 1.0.0

      # Build release AAB
      - name: Assemble Release Bundle
        run: ./gradlew :app:bundleRelease --stacktrace

      # Get the app version dynamically from the build
      - name: Get the app version dynamically from the build
        run: |
          VERSION=$(./gradlew -q printAppVersionName)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Sign the production bundle
      - name: Sign Android production release
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      # Rename APK
      - name: Rename APK
        run: mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/spacex-release_${VERSION}.aab

      # Deploy to Google Play
      - name: Deploy Bundle to google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH_JSON }}
          packageName: com.seancoyle.spacex
          releaseFiles: app/build/outputs/bundle/release/spacex-release_${{ env.VERSION }}.aab
          track: internal
          status: "completed"
          whatsNewDirectory: whatsNew