name: Generate Baseline Profile

on: workflow_call

jobs:
  generate-baseline-profile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Install GMD
      run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager "system-images;android-34;aosp_atd;x86_64"

    - name: Accept Android licenses
      run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Generate profile
      run: ./gradlew :app:generateBaselineProfile
