name: Generate Baseline Profile

on:
  workflow_dispatch:
  workflow_call:

jobs:
  generate-baseline-profile:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [ 33 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Enable KVM - Hardware Acceleration
      run: .github/scripts/ui_test_hardware_acceleration.sh

#    - name: Install GMD
#      run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager "system-images;android-34;aosp_atd;arm64-v8a"
#
#    - name: Accept Android licenses
#      run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Generate profile
      run: ./gradlew :app:generateBaselineProfile -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect --stacktrace
