name: Generate Bundles

on:
  workflow_call:

jobs:

  generateBundles:
    name: Generate APK's
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Assemble app debug APK
        run: |
          bash ./gradlew :app:assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-branch.apk
      - name: Upload branch APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-branch
          path: app/build/outputs/apk/debug/app-debug-branch.apk
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Assemble app debug APK
        run: |
          bash ./gradlew :app:assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug-main.apk
      - name: Upload app APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-main
          path: app/build/outputs/apk/debug/app-debug-main.apk