name: GitHub Release

on:
  workflow_dispatch:
    inputs:
      release-tag: { required: true, type: string, description: "Release Tag in format of v1.50.0" }
  workflow_call:
    inputs:
      release-tag: { required: true, type: string }

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ inputs.release-tag }}
          token: ${{ secrets.GH_TOKEN }}
