name: Deploy AAB to Play Store

on:
  workflow_dispatch:
    inputs:
      artifact-name: { required: true, type: string }

  workflow_call:
    inputs:
      artifact-name: { required: true, type: string }

jobs:
  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest

    steps:
      # Download Signed AAB
      - name: Download AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: app/build/outputs/bundle/release/

      # Deploy to Play store
      - name: Deploy Bundle to google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH_JSON }}
          packageName: com.seancoyle.spacex
          releaseFiles: app/build/outputs/bundle/release/${{ inputs.artifact-name }}
          track: internal
          status: "completed"
  #          whatsNewDirectory: whatsnew
