name: Release APK

on:
  workflow_call:

jobs:
  assemble-dev-release-apk:
    uses: ./.github/workflows/assemble_dev_release_apk.yml
    secrets: inherit

  comment-qr-code:
    uses: ./.github/workflows/comment_qr_code.yml
    needs: assemble-dev-release-apk
    secrets: inherit
    with:
      version: ${{ needs.assemble-dev-release-apk.outputs.version }}
