name: Tag Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git tag "v${{ inputs.version }}"
          git push origin "v${{ inputs.version }}"
