name: UI Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  uiTest:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 29 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Enable KVM - Hardware Acceleration
        run: .github/scripts/ui_test_hardware_acceleration.sh

      # Generates a list of modules which contain androidTest
      - name: Get UI test modules
        run: .github/scripts/ui_test_get_modules.sh

      # Runs UI tests and saves results to a log
      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: .github/scripts/ui_test_save_results.sh

      # Uploads the log file as an artifact
      - name: Upload UI Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-log
          path: ui-test-results.log

      # Publishes a summary table of the test results
      - name: Publish UI Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/build/outputs/androidTest-results/connected/**/*.xml'
          check_name: UI Test Results
#          fail_on_failure: true
