name: Unit Tests

on:
  workflow_call:

jobs:
  unitTest:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Runs unit tests
      - name: Unit tests
        run: .github/scripts/run_unit_tests.sh

      # Publishes a summary table of the test results
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: Unit Test Results
          fail_on_failure: true
