name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_name: { required: false, type: string, description: "Set versionName (e.g. 2.0.0)" }
      version_code: { required: false, type: string, description: "Set versionCode (e.g. 200)" }

  workflow_call:
    outputs:
      version:
        description: "The new version name"
        value: ${{ jobs.version-bump.outputs.version }}

jobs:
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.NEW_VERSION_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Version Bump
        id: version
        run: .github/scripts/version_bump.sh "${{ github.event.inputs.version_name }}" "${{ github.event.inputs.version_code }}"
