name: Version Bump

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      version:
        description: "The new version name"
        value: ${{ jobs.version-bump.outputs.version }}

jobs:
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.NEW_VERSION_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Version Bump
        id: version
        run: .github/scripts/version_bump.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: bump version to ${{ steps.version.outputs.NEW_VERSION_NAME }}"
          branch: version-bump/${{ steps.version.outputs.NEW_VERSION_NAME }}
          title: "chore: bump version to ${{ steps.version.outputs.NEW_VERSION_NAME }}"
          body: |
            This PR was automatically created to bump the app version to `${{ steps.version.outputs.NEW_VERSION_NAME }}`
          base: main
          delete-branch: true
          draft: false

      - name: Enable Auto-merge
        if: ${{ steps.cpr.outputs.pull-request-url != '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            gh pr merge "${{ steps.cpr.outputs.pull-request-url }}" --merge --auto